management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        # TODO Disable most endpoints in non-dev environments.
        include: '*'

spring:
  main:
    banner-mode: off
  application:
    name: Client A
  security:
    oauth2:
      client:
        registration:
          govsso:
            client-id: client-a
            client-secret: secreta
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          govsso:
            issuer-uri: https://gateway.localhost:13443/
server:
  # Use same port as govsso-session/docker-compose.yml.
  port: 11443
  ssl:
    enabled: true
    key-store-password: changeit
    key-store: src/main/resources/clienta-local-keystore.p12
    key-store-type: PKCS12
    trust-store: src/main/resources/clienta-local-truststore.p12
    trust-store-password: changeit

govsso:
  public-url: https://clienta.localhost:11443
  logo: client-a.png
